name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download tests repo war machine
      run: git clone https://github.com/Tripouille/gnlTester
    - name: run tests
      run: |
        cd gnlTester
        make m
