name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download tests repo war machine
      run: git clone https://github.com/Tripouille/gnlTester
    - name: Install valgrind
      run: sudo apt-get install -y valgrind
    - name: Install norm
      run: python3 -m pip install --upgrade pip setuptools && python3 -m pip install norminette
    - name: Run norm
      run: norminette
    - name: run tests
      run: |
        export TERM=xterm
        cd gnlTester
        make m
